### ISSUE TITLE
Equisetopsida not parent of Equisetidae 

### ISSUE THREAD

**Issue by hyanwong** [OpenTreeOfLife/feedback#281] opened 2016-05-11 22:48 UTC
this should presumably be a parent of https://tree.opentreeoflife.org/opentree/argus/opentree5.0@ott5662213/Equisetidae
# 

| Metadata | Do not edit below this line |
| :-- | :-- |
| Author | [None](https://github.com/hyanwong) |
| Upvotes | 0 |
| URL | [tree.opentreeoflife.org/opentree/argus/opentree5.0@ott719023/Equisetopsida](https://tree.opentreeoflife.org/opentree/argus/opentree5.0@ott719023/Equisetopsida) |
| Target node label | Equisetopsida |
| Synthetic tree id | opentree5.0 |
| Synthetic tree node id | ott719023 |
| Source tree id(s) |  |
| Open Tree Taxonomy id |  |
| Supporting reference | N/A |

**Comment by jar398** [comment] 2016-05-12 01:28
The problem is inherited from NCBI, where they are siblings. I think the
fix is to merge the two, or else to delete Equisetopsida (which has no
children and no rank, so smasher is treating it as an honorary species).

**Comment by hyanwong** [comment] 2016-05-12 10:05
Thanks. If they merge, which ID does the algorithm take?

**Comment by jar398** [comment] 2016-05-12 14:20
That depends on how the patch directive is written. The id will go with the
name, so if X merges into Y, then it will be Y with Y's id, otherwise the
other way around.

The merge will be recorded in forwards.tsv in the taxonomy distribution,
which I think is picked up by synthesis so that if an 'old' id is used as
an OTU, the new id will be substituted. See also
https://github.com/OpenTreeOfLife/taxomachine/issues/136

Since IRMNG, NCBI, and wikipedia seem to be so different, this could take
nontrivial research to resolve. It looks to me as if they might be applying
the same name to totally different taxa. What do you think the right
classification is?

**Comment by jar398** [comment] 2016-08-03 04:21
Notes to self:

According to EOL, Equisetopsida is used in two very different senses: either to refer to horsetails, or much more broadly to be all land plants (what NCBI calls Embryophyta).

NCBI Equisetopsida has no children. It should probably either be pruned, or inserted as parent of Equisetidae and child of Moniliformopses. Horsetails are simply Equisetidae, currently a sibling of Equisetopsida.

In GBIF, the name Equisetopsida (246) ~~seems to be used in yet a third way: as~~ is the sole member of Equisetophyta (61), with one genus, Equisetum. OTT synonymizes the two~~; I'm not sure why~~. Wikipedia puts Equisetum in Equisetidae (or rather Equisetaceae, which might be the same thing?). The current GBIF web UI says for Equisetophyta "Synonym of Tracheophyta" which makes no sense at all.

WoRMS Equisetopsida is a class containing Equisetidae and Bryidae. NCBI thinks Bryidae is a bryophyte (making this Equisetopsida a hodgepodge - WoRMS coverage of plants is sparse so it's hard to figure out what's intended).  So that's yet a fourth sense.

IRMNG has Equisetidae together with a bunch of extinct horsetail-like families in Equisetopsida. So that's a fifth sense. There is no Equisetophyta in IRMNG.

It's looking to me like:
(1) Nobody uses Equisetopsida in the Embryophyte sense, so forget about it.
(2) IRMNG seems to have a pretty clear idea of what Equisetopsida is: Equisetidae + extinct similar families.
(3) Equisetophyta is probably synonymous with Equisetopsida (or maybe introduced so that all ranks are filled out).

**Comment by jar398** [comment] 2016-08-03 12:20
oops, there _is_ only one genus of horsetails. so GBIF is fine. what confused me is that all the occurrences are in France http://www.gbif.org/species/61/. I thought that if it was all of horsetails there must be samples from elsewhere. It just has a biased sample I guess.

**Comment by jar398** [comment] 2016-10-12 14:36
Looks like this is fixed in OTT 2.10: There is only one Equisetopsida, and it is the parent of Equisetidae. https://tree.opentreeoflife.org/taxonomy/browse?name=Equisetopsida

**Closed as completed by jar398** 2016-10-12 14:36 UTC
Labels: Correction to names (taxonomy)
