### ISSUE TITLE
The snail shark

### ISSUE THREAD

**Issue by dufields** [OpenTreeOfLife/feedback#100] opened 2015-09-21 14:06 UTC
Dear Tree of Life,

Thank you for your work. As I study chondrichthyans, I naturally gravitated to the sharks and rays in your new tree and was startled to find a new species. Lymnea acuminata (placed within the Lamnidae) appears to have grown a spine, so to speak, and moved out of the gastropoda. Anyway, keep up the good work.

Regards,
Andrew

**Comment by jar398** [comment] 2015-09-21 14:27
Duplicate of feedback issue #74

**Comment by kcranston** [comment] 2015-09-21 14:29
Thanks for the feedback, though! (with comments off on the site, you wouldn't have seen the existing feedback).

**Closed as completed** 2015-11-09 14:44 UTC
Labels: duplicate, resolved
