### ISSUE TITLE
Lepisosteus_oculatus missing from vertebrate tree

### ISSUE THREAD

**Issue by iwanttobeabadger** [OpenTreeOfLife/feedback#241] opened 2016-03-20 06:00 UTC
When I search for spotted gar in the database, it returns the following error...

" This taxon is in our taxonomy but not in our tree synthesis database. This can happen for a variety of reasons, but the most probable is that is has a taxon flag (e.g. incertae sedis) that causes it to be pruned from the synthetic tree. See the taxonomy browser for more information about this taxon."

I am not sure why this error is being returned or why this species is being pruned. It should be there ... 
http://hgdownload.soe.ucsc.edu/goldenPath/hg19/multiz100way/hg19.100way.scientificNames.nh

Apologies if I'm missing something and many thanks in advance,

**Comment by mtholder** [comment] 2016-03-20 13:17
Thanks. This looks like a problem with our taxonomy. We are currently suppressing extinct taxa from the tree. That should not affect this species. However, the taxonomy combining software is erroneously treating Lepisosteiformes as a junior synonym of Semionotiformes (an extinct taxon).

See https://tree.opentreeoflife.org/taxonomy/browse?name=Lepisosteiformes 

We'll have to get that fixed in the next version of the taxonomy. I'll make an issue in the repository for that software tool, and link to this issue.  Thanks for the feedback.

**Comment by jar398** [comment] 2016-03-20 13:26
The software is fine; the problem is with NCBI, which thinks Semionotiformes is extant (contrary to IRMNG). We'll have to patch it since IRMNG has priority for extantness.

http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?name=Lepisosteiformes

**Comment by mtholder** [comment] 2016-03-20 15:46
NCBI says the gars are extant, which they are. All of the classified descendants of what NCBI calls Semionotiformes are in [Lepisosteidae](http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Tree&id=7915&lvl=3&lin=f&keep=1&srchmode=1&unlock).

But it is also clear the NCBI treats the taxa that other taxonomies refer to as "Lepisosteiformes" as being a part of Semionotiformes (see the synonymy listed [here](http://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=7914&lvl=3&lin=f&keep=1&srchmode=1&unlock) ).

It is also clear that IRMNG prefers to split these taxa into separate orders [Lepisoteiformes](http://www.marine.csiro.au/mirrorsearch/ir_search.list_family?ordername=Lepisosteiformes) and [Semionotiformes](http://www.marine.csiro.au/mirrorsearch/ir_search.list_family?ordername=Semionotiformes)

IRMNG labels Semionotiformes as extinct. This is correct for the set of taxa that IRMNG is referring to by the name "Semionotiformes"

IRMNG does not label Lepisoteiformes as extinct.

So (unless the inputs have change since when OTT 2.9 was built), it seems like there is plenty of correct, internally consistent information here. 

So I don't see how we can consider the software to be "fine". The software needs to be smart enough to know that the "extinct" label as used by IRMNG should only be applied to the set of descendants that IRMNG was talking about. 

_edited to fix missing close parentheses_

**Comment by jar398** [comment] 2016-06-22 23:35
The error has nothing to do with the way extinct flags are set. The bug is that IRMNG Semionotiformes is being equated with NCBI Semionotiformes when they are in fact consequentially distinct taxa. To repair this I will do something to prevent them from matching. (This is an example of why the current alignment method needs to be replaced with one that relies more heavily on membership than on names.)

**Closed as completed** 2016-10-11 19:54 UTC
Labels: taxon data in OTT, fixed in taxonomy draft
