### ISSUE TITLE
induced_subtree exception array index out of bounds

### ISSUE THREAD

**Issue by WisecaverLab** [OpenTreeOfLife/feedback#104] opened 2015-09-26 16:13 UTC
Hello,

I would like to pull out the induced subtree for 2,378 OTT ids, but when I try I get the following error

{
  "exception" : "ArrayIndexOutOfBoundsException",
  "fullname" : "java.lang.ArrayIndexOutOfBoundsException",
  "stacktrace" : [ ]
}

I can pull out smaller subtrees just fine. Is there are size limit for number of input ids? If so, what is it and would it be possible to increase it?

Thanks!
Jen

**Comment by kcranston** [comment] 2015-09-26 16:23
That's below the limit, so it should work. Can you give us a little more detail about how you are trying to do this? Through the website, or the APIs? A specific URL would be really helpful!

**Comment by jar398** [comment] 2015-09-26 16:48
Sounds like a bug on our side. Our log files don't capture either the
request or the error details - I just looked and I see information about
processing the request but nothing about the outcome. I wonder if you could
transmit the full POST request to use somehow, with the JSON you used for
the ids. You could put it in pastebin.com, as a gist on github, in dropbox
(you can send to me personally if you like), or if none of those methods
work for you, pasted directly into this issue discussion on github. That
would help us to reproduce and diagnose the problem.

Thanks
Jonathan

**Comment by WisecaverLab** [comment] 2015-09-26 16:58
Thanks for the quick response.

Here's a link to my POST http://pastebin.com/2WGi1y9Y

Thanks for the help!

**Comment by kcranston** [comment] 2015-09-26 19:17
@blackrim or @josephwb : assuming this is a treemachine error, any ideas? This is the induced_subtree method. Is there an undocumented upper bound on the number of species?

As a workaround, @JenWisecaver you could use the [subtree](https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#subtree_tree) call to get the whole subtree and then prune the unwanted tips using R or python. There are also some select subtrees for direct download posted on the [release page](http://files.opentreeoflife.org/trees/).

**Comment by jimallman** [comment] 2015-09-26 20:42
> Is there an undocumented upper bound on the number of species?

I don't seen any upper limit in [the induced_subtree code](https://github.com/OpenTreeOfLife/treemachine/blob/2214f2ae435991f968c5ad555a78f42247a7b895/src/main/java/opentree/plugins/tree_of_life.java#L236). I did have good results submitting just the first half of the query, so my guesses are:
- a bad/missing ottid that acts as a "poison pill" when [we call ge.findGraphTaxNodeByUID](https://github.com/OpenTreeOfLife/treemachine/blob/2214f2ae435991f968c5ad555a78f42247a7b895/src/main/java/opentree/plugins/tree_of_life.java#L288)
- a hard size limit on POSTed JSON (though this seems unlikely, given the much larger Nexson payloads we're working with

**Comment by jimallman** [comment] 2015-09-26 21:15
I spent a few minutes on the "poison pill" notion above, testing with chunks of the original ottid list to see which failed. I had narrowed down a chunk of the first thousand (the ids from position 900-1000) as a failing block, so was trying to split that as a further test. The results were not what I'd expect from a single bad ottid:

#### 900-1000 &mdash; FAILS

I found that this range of ids reliably fails the curl call:

> curl -X POST http://api.opentreeoflife.org/v2/tree_of_life/induced_subtree -H "content-type:application/json" -d '{"ott_ids":[5171713, 665269, 516739, 929449, 259422, 142777, 534551, 142773, 1015148, 1084888, 489171, 489173, 1015149, 489169, 63017, 602652, 63016, 193608, 583982, 54063, 489172, 12785, 5238774, 5378239, 101142, 840689, 876140, 54064, 54062, 489170, 54067, 489177, 489174, 54079, 326669, 489175, 54080, 654465, 489176, 1015146, 1015147, 1015144, 675573, 84405, 500398, 500404, 239479, 76268, 5289034, 244677, 181271, 1080732, 786505, 5240046, 5393559, 5393560, 80096, 58146, 5393558, 748274, 77285, 181218, 685200, 4785794, 348644, 250482, 767454, 164334, 1011244, 569130, 1011241, 569127, 5174046, 5237047, 56342, 5239667, 5282684, 929095, 5239666, 853516, 77906, 187089, 303572, 4779381, 4786216, 303966, 559469, 5240003, 526147, 222933, 323351, 248588, 559499, 279481, 490355, 4784952, 1074357, 4777251, 4776235, 273958]}'

#### 900-950                     WORKS

Next, we split this in half and test the first half (working our way to the final bad id):

> curl -X POST http://api.opentreeoflife.org/v2/tree_of_life/induced_subtree -H "content-type:application/json" -d '{"ott_ids":[5171713, 665269, 516739, 929449, 259422, 142777, 534551, 142773, 1015148, 1084888, 489171, 489173, 1015149, 489169, 63017, 602652, 63016, 193608, 583982, 54063, 489172, 12785, 5238774, 5378239, 101142, 840689, 876140, 54064, 54062, 489170, 54067, 489177, 489174, 54079, 326669, 489175, 54080, 654465, 489176, 1015146, 1015147, 1015144, 675573, 84405, 500398, 500404, 239479, 76268, 5289034, 244677]}'

#### 950-1000                    WORKS

But wait! Both halves of the failing series work when submitted separately!

> curl -X POST http://api.opentreeoflife.org/v2/tree_of_life/induced_subtree -H "content-type:application/json" -d '{"ott_ids":[181271, 1080732, 786505, 5240046, 5393559, 5393560, 80096, 58146, 5393558, 748274, 77285, 181218, 685200, 4785794, 348644, 250482, 767454, 164334, 1011244, 569130, 1011241, 569127, 5174046, 5237047, 56342, 5239667, 5282684, 929095, 5239666, 853516, 77906, 187089, 303572, 4779381, 4786216, 303966, 559469, 5240003, 526147, 222933, 323351, 248588, 559499, 279481, 490355, 4784952, 1074357, 4777251, 4776235, 273958]}'

This suggests some kind of interaction between one-or-more nodes in each set of 50. I don't see any interaction in [the code, which seems to process each id in isolation](https://github.com/OpenTreeOfLife/treemachine/blob/2214f2ae435991f968c5ad555a78f42247a7b895/src/main/java/opentree/plugins/tree_of_life.java#L285-L302), but that's where the clues are pointing. There's simply not much else going on in `induced_subtree()`. Also possibly of interest: there **is** an unusual ottid in the second half (950-1000), since the response includes this:
`"ott_ids_not_in_graph" : [ 4776235 ],`

**Comment by jimallman** [comment] 2015-09-26 21:19
Oh, I overlooked [the final step (subtree extraction and Newick generation)](https://github.com/OpenTreeOfLife/treemachine/blob/2214f2ae435991f968c5ad555a78f42247a7b895/src/main/java/opentree/plugins/tree_of_life.java#L323), which is presumably where things are going wrong. Perhaps [this exception noted in the wiki](https://github.com/OpenTreeOfLife/opentree/wiki/Open-Tree-of-Life-APIs#induced_subtree)?

> WARNING: there is currently a known bug if any of the input nodes is the parent of another, the returned tree may be incorrect. Please avoid this input case.

**Comment by WisecaverLab** [comment] 2015-09-26 21:52
Yes! I'm sorry that solved it. Before, I had noted the exception in the wiki and did skip OTTs that were direct parents of other OTTs in my list. But I didn't think to look for OTTs that were parents of parents of other OTTs. Thanks so much for helping me spot the error.

**Comment by josephwb** [comment] 2015-09-27 13:29
Treemachine should detect this problem and either 1) return the error or 2) skip the offensive taxa. What do people want here?

**Comment by WisecaverLab** [comment] 2015-09-27 13:40
From a user's perspective, it would be awesome if the taxa were skipped with the additional JSON return value 

  "interior_nodes_skipped" : [ ],

or something along those lines. But I can make it work either way. Thanks.

**Comment by jar398** [comment] 2015-09-27 15:51
It seems to be that the induced tree is perfectly well defined even if the
input contains ancestor/descendant related pairs. It's not an error
situation. Ideally the method would return this induced tree.

But if it can't, some kind of error message (and a 4xx response) would be
the best result.

It may be that some of the input nodes do not end up being tips of the
returned tree. But there's no rule that says that they have to be. The
induced tree is just supposed to be the smallest compatible tree containing
the given nodes.

**Comment by jar398** [comment] 2016-06-22 20:21
@josephwb reports that this bug is fixed now.

**Closed as completed by jar398** 2016-06-22 20:21 UTC
Labels: bug (software only)
