### ISSUE TITLE
Ant subfamilies

### ISSUE THREAD

**Issue by opentreeapi** [OpenTreeOfLife/feedback#347] opened 2017-04-10 21:09 UTC
Hello,
I'm looking at ants (Formicidae) in the tree. While I can see some information for genuses, the relationships aren't well resolved. In particular, the known subfamilies of ants aren't clearly separated. Would incorporating that kind of information be relevant here? 

Some references include: 
 - review: http://annualreviews.org/doi/full/10.1146/annurev-ecolsys-120213-091824#f2
 - overview (with nex file as supp if I remember correctly): http://onlinelibrary.wiley.com/doi/10.1111/evo.12105/full
 - subfamily-specific phylogenies are also availablle from Phil Ward.

Thanks and kind regards,
Yannick

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [yannick wurm](mailto:y.wurm@qmul.ac.uk) 
Upvotes   |   0 
URL   |   [tree.opentreeoflife.org/opentree/argus/ottol@215086/Formicidae](https://tree.opentreeoflife.org/opentree/argus/ottol@215086/Formicidae) 
Target node label   |   Formicidae 
Synthetic tree id   |   opentree9.1 
Synthetic tree node id   |   ott215086 
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   na

**Comment by mtholder** [comment] 2017-04-11 19:44
Thanks for the pointers. I've started to add the Moreau and Bell 2013 tree at: https://tree.opentreeoflife.org/curator/study/edit/ot_1056 we should be able to get that one at least in the supertree build the next time we run it.
I'll contact Dr. Ward to see if we can get some tree files from the other papers.

**Comment by arlin** [comment] 2018-04-12 15:51
@mtholder, I'm looking for trees to add from the suggestion list and I noticed this.  What would it take to close this ticket?   You have added the tree from Moreau, et al. 2013, and it has been curated, and it is staged for inclusion.  There are about 14 ant phylogeny studies in TreeBASE with author P. Ward.  I could add some of these.  I could not quickly assess which are in OpenTree because when I filter the study list on "ward" I get about 150 studies (not sure why so many).  By browsing the list, I would guess that OpenTree has a few small studies on ants from author P. Ward such as Brady, et al 2006 or Ward and Sumnicht.

**Comment by arlin** [comment] 2018-04-12 15:57
Compiling a list of TreeBASE studies by P. Ward 
* S10012 - needs curation (https://tree.opentreeoflife.org/curator/study/view/pg_1950)
* S12022 - needs curation (https://tree.opentreeoflife.org/curator/study/view/pg_2331)
* S1218 - needs curation (https://tree.opentreeoflife.org/curator/study/view/pg_2069)
* S12813 - needs curation (https://tree.opentreeoflife.org/curator/study/view/pg_2179)
* S1312 - needs curation (https://tree.opentreeoflife.org/curator/study/view/pg_2091)
* S15764 - not uploaded yet
* S1720 - **included** (https://tree.opentreeoflife.org/curator/study/view/pg_1849)
* S17550 - just uploaded this, needs curation (https://tree.opentreeoflife.org/curator/study/view/ot_1245)
* S18146 - not uploaded yet
* S18604 - not uploaded yet 
* S18847 - not uploaded yet
* S966 - needs curation (https://tree.opentreeoflife.org/curator/study/view/pg_1811)

There are also 6 data packages on ants from P. Ward in Dryad.  One of them is in TreeBASE: Chomicki et al is S17550.  I checked and all of these have trees in them (not just pictures of trees)
* Branstetter, et al. (2017) https://doi.org/10.5061/dryad.89n87  - **queued** (https://tree.opentreeoflife.org/curator/study/view/ot_1059)
* Branstetter (2017) https://doi.org/10.5061/dryad.r8d4q  - not uploaded 
* Ward PS, Branstetter MG (2017) https://doi.org/10.5061/dryad.3d31q  -  not uploaded 
* Johnson (2013)  https://doi.org/10.5061/dryad.jt440  - not uploaded
* Brady  (2014)  https://doi.org/10.5061/dryad.3df32  - not uploaded
* Chomicki G, Ward PS, Renner SS (2015) - see above S17550 

So, 1 included, 1 queued, 7 needing curation, 4 than can be auto-uploaded from TreeBASE which is easy, 4 more that would require unknown amount of effort to identify and upload the desired tree from Dryad archive (these seem to have several dozen trees in each archive).

**Comment by mtholder** [comment] 2018-04-12 16:45
sounds great. Thanks, @arlin . I think that we can close this after we build the next version of the tree.

**Comment by arlin** [comment] 2018-04-12 21:29
Doing some of the curating now
* ot_1245 Chomicki 2015 (S17550) - mapped taxa, identified ingroup, method, scale; just need to set root (I have contacted author). 
* ot_1247 Ward, et al. 2015 (S15764) - added, fixed citation, did some mapping, verified root.  
* S18146 - error uploading  
* ot_1248 Boudinot, et al. (S18604) -added, updated citation, mapped taxa, identified ingroup, method, scale.  just needs root. 
* ot_1249 Ward & Fisher 2016 (S18847) - added, updated citation, rooted tree, identified ingroup, method, just needs license

**Comment by jar398** [comment] 2018-04-13 00:35
If you could add DOIs whenever you're looking at a study without one that would be wonderful. As I remember only about 50% of Treebase studies have DOIs in their records, but most (not all) fo the rest have DOIs that just aren't recorded.. I harvested a bunch of these DOIs when I did a batch lookup over the phylografter database back in 2013, but I know many DOI-missing studies remain. I recently came across a 2018 study where the curator didn't enter the DOI, which sort of baffles me.

DOIs give a stable link and machine-readable metadata, and are our best way to check for duplicates. You can usually find the DOI by visiting the article or its landing page. end of sermon.

**Comment by arlin** [comment] 2018-04-13 18:58
The error uploaded S18146 has been reported in OpenTreeOfLife/opentree#362

**Comment by arlin** [comment] 2018-04-13 18:59
yes @jar398 I'm making sure everything has a DOI.

**Comment by arlin** [comment] 2018-04-13 21:17
With email information from author Philip Ward, finished ot_1245 Chomicki 2015 (S17550) and ot_1248 Boudinot, et al. (S18604).  

These 2 are now in the queue for synthesis.

**Comment by arlin** [comment] 2018-04-13 21:45
Ward & Fisher 2016 (S18847) is now in the queue for synthesis.

**Comment by arlin** [comment] 2018-04-25 16:14
@mtholder, I was talking with the OP today and this turns out to be an issue with discoverability.  Actually the ant subfamilies (https://en.wikipedia.org/wiki/List_of_ant_subfamilies) are mostly in the current synth tree (except the extinct ones) and they are distinguished.  See the phylogeny of representative species below from phylotastic.  The problem is that it is very hard to see this with the viewer.  Is there some way to adjust the settings to show more levels, and maybe to highlight subfamilies?  

![ant_subfamilies](https://user-images.githubusercontent.com/1659198/39258428-f6acc164-4881-11e8-98c6-b626fca53622.png)

**Comment by mtholder** [comment] 2018-05-02 22:35
see https://github.com/OpenTreeOfLife/germinator/issues/116 and https://github.com/OpenTreeOfLife/treemachine/issues/232

**Comment by mtholder** [comment] 2024-05-27 17:18
closing because we've added the ant trees targeted and created more specific issues for the UI problems.

**Closed as completed by mtholder** 2024-05-27 17:18 UTC
Labels: Suggest a phylogeny to incorporate
