### ISSUE TITLE
Allow the search for known familiar animals

### ISSUE THREAD

**Issue by Programmer96** [OpenTreeOfLife/feedback#365] opened 2017-09-02 11:05 UTC
Like chicken, dog, horse, etc.

================================================
Metadata   |   Do not edit below this line
:------------|:----------
Author   |   [None](https://github.com/Programmer96) 
Upvotes   |   0 
URL   |   [/contact](None/contact) 
Target node label   |    
Synthetic tree id   |    
Synthetic tree node id   |    
Source tree id(s)   |    
Open Tree Taxonomy id   |    
Supporting reference   |   None

**Comment by jar398** [comment] 2017-09-03 02:45
related: https://github.com/OpenTreeOfLife/reference-taxonomy/issues/160

**Comment by mtholder** [comment] 2024-05-27 19:05
closed as duplicate of https://github.com/OpenTreeOfLife/reference-taxonomy/issues/160

**Closed as completed by mtholder** 2024-05-27 19:05 UTC
